### ISSUE TITLE
Compiling container services doesn't finish on shared hosting Hetzner

### ISSUE THREAD

**Issue by leoloso** [GatoGraphQL/GatoGraphQL#2631]
As reported by Ivan, when installing Gato GraphQL v1.5.4 on a shared hosting plan on [Hetzner](https://www.hetzner.com/) it produces an error.

The reason is that the script takes too long to execute, so it reaches a max execution time from PHP, which is a fatal error (can't be `catch`):

```
[20-Jan-2024 18:01:53 UTC] PHP Warning:  Uncaught ReflectionException: Method PoPCMSSchema\CustomPostMediaMutations\TypeResolvers\UnionType\RootSetFeaturedImageOnCustomPostMutationErrorPayloadUnionTypeResolver::getInstanceManager does not have a prototype in /usr/www/users/appstaa/wp-content/plugins/gatographql/vendor/symfony/dependency-injection/Compiler/AutowireRequiredMethodsPass.php:74
Stack trace:
#0 /usr/www/users/appstaa/wp-content/plugins/gatographql/vendor/symfony/dependency-injection/Compiler/AutowireRequiredMethodsPass.php(74): ReflectionMethod->getPrototype()
#1 /usr/www/users/appstaa/wp-content/plugins/gatographql/vendor/symfony/dependency-injection/Compiler/AbstractRecursivePass.php(95): PrefixedByPoP\Symfony\Component\DependencyInjection\Compiler\AutowireRequiredMethodsPass->processValue()
#2 /usr/www/users/appstaa/wp-content/plugins/gatographql/vendor/symfony/dependency-injection/Compiler/AutowireRequiredMethodsPass.php(33): PrefixedByPoP\Symfony\Component\DependencyInjection\Compiler\AbstractRecursivePass->processValue()
#3 /usr/www/users/appstaa/wp-content/plugins/gatographql/vendor/symfony/dependency-injection/Compiler/AbstractRecursivePass.php(56): PrefixedByPoP\Symfony\Component\DependencyInjection\Compiler\AutowireRequiredMethodsPass->processValue()
#4 /usr/www/users/appstaa/wp-content/plugins/gatographql/vendor/symfony/dependency-injection/Compiler/Compiler.php(80): PrefixedByPoP\Symfony\Component\DependencyInjection\Compiler\AbstractRecursivePass->process()
#5 /usr/www/users/appstaa/wp-content/plugins/gatographql/vendor/symfony/dependency-injection/ContainerBuilder.php(668): PrefixedByPoP\Symfony\Component\DependencyInjection\Compiler\Compiler->compile()
#6 /usr/www/users/appstaa/wp-content/plugins/gatographql/vendor/getpop/root/src/Container/ContainerBuilderFactoryTrait.php(147): PrefixedByPoP\Symfony\Component\DependencyInjection\ContainerBuilder->compile()
#7 /usr/www/users/appstaa/wp-content/plugins/gatographql/vendor/getpop/root/src/AppLoader.php(405): PoP\Root\Container\ContainerBuilderFactory->maybeCompileAndCacheContainer()
#8 /usr/www/users/appstaa/wp-content/plugins/gatographql/src/PluginSkeleton/AbstractMainPlugin.php(1669): PoP\Root\AppLoader->bootApplication()
#9 /usr/www/users/appstaa/wp-content/plugins/gatographql/src/PluginSkeleton/AbstractMainPlugin.php(1584): GatoGraphQL\GatoGraphQL\PluginSkeleton\AbstractMainPlugin->bootApplication()
#10 /usr/www/users/appstaa/wp-includes/class-wp-hook.php(324): GatoGraphQL\GatoGraphQL\PluginSkeleton\AbstractMainPlugin->GatoGraphQL\GatoGraphQL\PluginSkeleton\{closure}()
#11 /usr/www/users/appstaa/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters()
#12 /usr/www/users/appstaa/wp-includes/plugin.php(517): WP_Hook->do_action()
#13 /usr/www/users/appstaa/wp-content/plugins/gatographql/src/PluginApp.php(34): do_action()
#14 /usr/www/users/appstaa/wp-includes/class-wp-hook.php(324): GatoGraphQL\GatoGraphQL\PluginApp::GatoGraphQL\GatoGraphQL\{closure}()
#15 /usr/www/users/appstaa/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters()
#16 /usr/www/users/appstaa/wp-includes/plugin.php(517): WP_Hook->do_action()
#17 /usr/www/users/appstaa/wp-settings.php(506): do_action()
#18 /usr/www/users/appstaa/wp-config.php(110): require_once('/usr/www/users/...')
#19 /usr/www/users/appstaa/wp-load.php(50): require_once('/usr/www/users/...')
#20 /usr/www/users/appstaa/wp-admin/admin.php(34): require_once('/usr/www/users/...')
#21 /usr/www/users/appstaa/wp-admin/plugins.php(10): require_once('/usr/www/users/...')
#22 {main}
  thrown in /usr/www/users/appstaa/wp-content/plugins/gatographql/vendor/symfony/dependency-injection/Compiler/AutowireRequiredMethodsPass.php on line 74
[20-Jan-2024 18:01:53 UTC] PHP Stack trace:
[20-Jan-2024 18:01:53 UTC] PHP   1. {main}() /usr/www/users/appstaa/wp-admin/plugins.php:0
[20-Jan-2024 18:01:53 UTC] PHP   2. require_once() /usr/www/users/appstaa/wp-admin/plugins.php:10
[20-Jan-2024 18:01:53 UTC] PHP   3. require_once() /usr/www/users/appstaa/wp-admin/admin.php:34
[20-Jan-2024 18:01:53 UTC] PHP   4. require_once() /usr/www/users/appstaa/wp-load.php:50
[20-Jan-2024 18:01:53 UTC] PHP   5. require_once() /usr/www/users/appstaa/wp-config.php:110
[20-Jan-2024 18:01:53 UTC] PHP   6. do_action($hook_name = 'plugins_loaded') /usr/www/users/appstaa/wp-settings.php:506
[20-Jan-2024 18:01:53 UTC] PHP   7. WP_Hook->do_action($args = [0 => '']) /usr/www/users/appstaa/wp-includes/plugin.php:517
[20-Jan-2024 18:01:53 UTC] PHP   8. WP_Hook->apply_filters($value = '', $args = [0 => '']) /usr/www/users/appstaa/wp-includes/class-wp-hook.php:348
[20-Jan-2024 18:01:53 UTC] PHP   9. GatoGraphQL\GatoGraphQL\PluginApp::GatoGraphQL\GatoGraphQL\{closure:/usr/www/users/appstaa/wp-content/plugins/gatographql/src/PluginApp.php:33-38}('') /usr/www/users/appstaa/wp-includes/class-wp-hook.php:324
[20-Jan-2024 18:01:53 UTC] PHP  10. do_action($hook_name = 'GatoGraphQL\\GatoGraphQL\\PluginAppHooks:initializeApp', ...$arg = variadic('external')) /usr/www/users/appstaa/wp-content/plugins/gatographql/src/PluginApp.php:34
[20-Jan-2024 18:01:53 UTC] PHP  11. WP_Hook->do_action($args = [0 => 'external']) /usr/www/users/appstaa/wp-includes/plugin.php:517
[20-Jan-2024 18:01:53 UTC] PHP  12. WP_Hook->apply_filters($value = '', $args = [0 => 'external']) /usr/www/users/appstaa/wp-includes/class-wp-hook.php:348
[20-Jan-2024 18:01:53 UTC] PHP  13. GatoGraphQL\GatoGraphQL\PluginSkeleton\AbstractMainPlugin->GatoGraphQL\GatoGraphQL\PluginSkeleton\{closure:/usr/www/users/appstaa/wp-content/plugins/gatographql/src/PluginSkeleton/AbstractMainPlugin.php:1580-1585}($pluginAppGraphQLServerName = 'external') /usr/www/users/appstaa/wp-includes/class-wp-hook.php:324
[20-Jan-2024 18:01:53 UTC] PHP  14. GatoGraphQL\GatoGraphQL\PluginSkeleton\AbstractMainPlugin->bootApplication($pluginAppGraphQLServerName = 'external') /usr/www/users/appstaa/wp-content/plugins/gatographql/src/PluginSkeleton/AbstractMainPlugin.php:1584
[20-Jan-2024 18:01:53 UTC] PHP  15. PoP\Root\AppLoader->bootApplication() /usr/www/users/appstaa/wp-content/plugins/gatographql/src/PluginSkeleton/AbstractMainPlugin.php:1669
[20-Jan-2024 18:01:53 UTC] PHP  16. PoP\Root\Container\ContainerBuilderFactory->maybeCompileAndCacheContainer($compilerPasses]) /usr/www/users/appstaa/wp-content/plugins/gatographql/vendor/getpop/root/src/AppLoader.php:405
[20-Jan-2024 18:01:53 UTC] PHP  17. PrefixedByPoP\Symfony\Component\DependencyInjection\ContainerBuilder->compile($resolveEnvPlaceholders = *uninitialized*) /usr/www/users/appstaa/wp-content/plugins/gatographql/vendor/getpop/root/src/Container/ContainerBuilderFactoryTrait.php:147
[20-Jan-2024 18:01:53 UTC] PHP  18. PrefixedByPoP\Symfony\Component\DependencyInjection\Compiler\Compiler->compile($container) /usr/www/users/appstaa/wp-content/plugins/gatographql/vendor/symfony/dependency-injection/ContainerBuilder.php:668
[20-Jan-2024 18:01:53 UTC] PHP  19. PrefixedByPoP\Symfony\Component\DependencyInjection\Compiler\AbstractRecursivePass->process($container) /usr/www/users/appstaa/wp-content/plugins/gatographql/vendor/symfony/dependency-injection/Compiler/Compiler.php:80
[20-Jan-2024 18:01:53 UTC] PHP  20. PrefixedByPoP\Symfony\Component\DependencyInjection\Compiler\AutowireRequiredMethodsPass->processValue($value) /usr/www/users/appstaa/wp-content/plugins/gatographql/vendor/symfony/dependency-injection/Compiler/AbstractRecursivePass.php:56
[20-Jan-2024 18:01:53 UTC] PHP  21. PrefixedByPoP\Symfony\Component\DependencyInjection\Compiler\AbstractRecursivePass->processValue($value) /usr/www/users/appstaa/wp-content/plugins/gatographql/vendor/symfony/dependency-injection/Compiler/AutowireRequiredMethodsPass.php:33
[20-Jan-2024 18:01:53 UTC] PHP  22. PrefixedByPoP\Symfony\Component\DependencyInjection\Compiler\AutowireRequiredMethodsPass->processValue($value) /usr/www/users/appstaa/wp-content/plugins/gatographql/vendor/symfony/dependency-injection/Compiler/AbstractRecursivePass.php:95
[20-Jan-2024 18:01:53 UTC] PHP Fatal error:  Maximum execution time of 60 seconds exceeded in /usr/www/users/appstaa/wp-content/plugins/gatographql/vendor/symfony/dependency-injection/Compiler/AutowireRequiredMethodsPass.php on line 75
[20-Jan-2024 18:01:53 UTC] PHP Stack trace:
[20-Jan-2024 18:01:53 UTC] PHP   1. {main}() /usr/www/users/appstaa/wp-admin/plugins.php:0
[20-Jan-2024 18:01:53 UTC] PHP   2. require_once() /usr/www/users/appstaa/wp-admin/plugins.php:10
[20-Jan-2024 18:01:53 UTC] PHP   3. require_once() /usr/www/users/appstaa/wp-admin/admin.php:34
[20-Jan-2024 18:01:53 UTC] PHP   4. require_once() /usr/www/users/appstaa/wp-load.php:50
[20-Jan-2024 18:01:53 UTC] PHP   5. require_once() /usr/www/users/appstaa/wp-config.php:110
[20-Jan-2024 18:01:53 UTC] PHP   6. do_action($hook_name = 'plugins_loaded') /usr/www/users/appstaa/wp-settings.php:506
[20-Jan-2024 18:01:53 UTC] PHP   7. WP_Hook->do_action($args = [0 => '']) /usr/www/users/appstaa/wp-includes/plugin.php:517
[20-Jan-2024 18:01:53 UTC] PHP   8. WP_Hook->apply_filters($value = '', $args = [0 => '']) /usr/www/users/appstaa/wp-includes/class-wp-hook.php:348
[20-Jan-2024 18:01:53 UTC] PHP   9. GatoGraphQL\GatoGraphQL\PluginApp::GatoGraphQL\GatoGraphQL\{closure:/usr/www/users/appstaa/wp-content/plugins/gatographql/src/PluginApp.php:33-38}('') /usr/www/users/appstaa/wp-includes/class-wp-hook.php:324
[20-Jan-2024 18:01:53 UTC] PHP  10. do_action($hook_name = 'GatoGraphQL\\GatoGraphQL\\PluginAppHooks:initializeApp', ...$arg = variadic('external')) /usr/www/users/appstaa/wp-content/plugins/gatographql/src/PluginApp.php:34
[20-Jan-2024 18:01:53 UTC] PHP  11. WP_Hook->do_action($args = [0 => 'external']) /usr/www/users/appstaa/wp-includes/plugin.php:517
[20-Jan-2024 18:01:53 UTC] PHP  12. WP_Hook->apply_filters($value = '', $args = [0 => 'external']) /usr/www/users/appstaa/wp-includes/class-wp-hook.php:348
[20-Jan-2024 18:01:53 UTC] PHP  13. GatoGraphQL\GatoGraphQL\PluginSkeleton\AbstractMainPlugin->GatoGraphQL\GatoGraphQL\PluginSkeleton\{closure:/usr/www/users/appstaa/wp-content/plugins/gatographql/src/PluginSkeleton/AbstractMainPlugin.php:1580-1585}($pluginAppGraphQLServerName = 'external') /usr/www/users/appstaa/wp-includes/class-wp-hook.php:324
[20-Jan-2024 18:01:53 UTC] PHP  14. GatoGraphQL\GatoGraphQL\PluginSkeleton\AbstractMainPlugin->bootApplication($pluginAppGraphQLServerName = 'external') /usr/www/users/appstaa/wp-content/plugins/gatographql/src/PluginSkeleton/AbstractMainPlugin.php:1584
[20-Jan-2024 18:01:53 UTC] PHP  15. PoP\Root\AppLoader->bootApplication() /usr/www/users/appstaa/wp-content/plugins/gatographql/src/PluginSkeleton/AbstractMainPlugin.php:1669
[20-Jan-2024 18:01:53 UTC] PHP  16. PoP\Root\Container\ContainerBuilderFactory->maybeCompileAndCacheContainer($compilerPasses]) /usr/www/users/appstaa/wp-content/plugins/gatographql/vendor/getpop/root/src/AppLoader.php:405
[20-Jan-2024 18:01:53 UTC] PHP  17. PrefixedByPoP\Symfony\Component\DependencyInjection\ContainerBuilder->compile($resolveEnvPlaceholders = *uninitialized*) /usr/www/users/appstaa/wp-content/plugins/gatographql/vendor/getpop/root/src/Container/ContainerBuilderFactoryTrait.php:147
[20-Jan-2024 18:01:53 UTC] PHP  18. PrefixedByPoP\Symfony\Component\DependencyInjection\Compiler\Compiler->compile($container) /usr/www/users/appstaa/wp-content/plugins/gatographql/vendor/symfony/dependency-injection/ContainerBuilder.php:668
[20-Jan-2024 18:01:53 UTC] PHP  19. PrefixedByPoP\Symfony\Component\DependencyInjection\Compiler\AbstractRecursivePass->process($container) /usr/www/users/appstaa/wp-content/plugins/gatographql/vendor/symfony/dependency-injection/Compiler/Compiler.php:80
[20-Jan-2024 18:01:53 UTC] PHP  20. PrefixedByPoP\Symfony\Component\DependencyInjection\Compiler\AutowireRequiredMethodsPass->processValue($value) /usr/www/users/appstaa/wp-content/plugins/gatographql/vendor/symfony/dependency-injection/Compiler/AbstractRecursivePass.php:56
[20-Jan-2024 18:01:53 UTC] PHP  21. PrefixedByPoP\Symfony\Component\DependencyInjection\Compiler\AbstractRecursivePass->processValue($value) /usr/www/users/appstaa/wp-content/plugins/gatographql/vendor/symfony/dependency-injection/Compiler/AutowireRequiredMethodsPass.php:33
[20-Jan-2024 18:01:53 UTC] PHP  22. PrefixedByPoP\Symfony\Component\DependencyInjection\Compiler\AutowireRequiredMethodsPass->processValue($value) /usr/www/users/appstaa/wp-content/plugins/gatographql/vendor/symfony/dependency-injection/Compiler/AbstractRecursivePass.php:95
```

**Comment by leoloso** [comment]
_(This if further feedback by Ivan)_

A difficult situation to troubleshoot, indeed. However, let's separate the observations into two:
1. My Hetzner issue was with the execution time
2. My Racknerd issue was with hitting the memory limit

My Hetzner WP installation is permanent, so I de-installed the main plugin, reduced the PHP memory limit back to 40M (I confirmed with a PHP script that outputs ini_get() like you do) and re-installed it; this time the installation completed without issue, however it took more than 60 seconds again.

My Racknerd WP installation was ephemeral: I installed WordPress via the Softaculous WP Manager which comes with the cPanel but then removed it because I thought I would not be needing it, which was possibly a bad decision.

However, returning to the two observations, it appears the memory limit issue is spurious. If you could somehow improve the activation procedure so that it recovers from a failed installation due to hitting the memory limit, that would be great; but if not, it is possible that it will not be a big issue in the grand scheme of things.

The activation duration however appears to me more important. To reiterate, I tried 3 deployments:
-- the first one (Hetzner) required more than 60 seconds;
-- the second (WPX.net, expensive host with very high resource limits even on the cheapest plan, they allow a customer's site to keep a whole CPU core at 100% for up to 24 hours before they intervene) took more than 10 seconds to deploy;
-- the last one, the dinky Racknerd at $9.98 per year (!!!) finished activation visibly faster than WPX, at 3-4 seconds, tops.

Additionally, on my Hetzner install, where I had CloudFlare proxy enabled, the first time the plugin activated successfully, I got an http 524 error because apparently CF lost connection with the origin. But a 524 error is not a permanent error, and a page refresh fixes it — unlike the memory limit error which breaks the PHP thread completely and bricks the site.

Anyway it seems to me the speed of activation and possible timeouts is the more important issue to figure out and solve. Any attention worth paying should be addressed towards working past possible slow hosts, or at least issue warning with max_execution_time is set under 60 seconds, just to be safe.

Ideally (speaking strictly as a user; I have no idea if/how this can be managed in reality) in the case of a crash due to exceeded execution time, the activation routine should be able to stand up on its own, dust itself off and continue.
